Lab-2
AndrewZzz24/WebProgrammingUniversityCourse pull request #2
Opened 2022-10-16 21:01 UTC by AndrewZzz24

Lab-2 Andrew Zmushko M33031

2022-10-17 11:19 UTC, BakasaRus requested changes
Отсутствует `font-style` (попробуй сделать текст курсивным через CSS)

2022-10-17 11:19 UTC, BakasaRus commented on Sources/Styles/Layouts/body.css
> +    display: flex;
Зачем...

2022-10-17 11:19 UTC, BakasaRus commented on index.html
> +        </nav>
Вот тут можно сделать сложный селектор, который выберет все ссылки внутри навигации с этим классом (чтобы не нужно было у каждой ссылки ставить класс)

2022-10-17 11:19 UTC, BakasaRus commented on Sources/Styles/Layouts/main.css
> +    font-family: Calibri, sans-serif;
Этот шрифт нужно поменять на имеющийся в Google Fonts

2022-10-17 11:19 UTC, BakasaRus commented on Sources/Styles/Layouts/footer.css
> +    padding: 15px 1em 15px 1em;
Что за `em`? Какие аналогичные единицы измерения есть и где они используются?

2022-10-17 11:19 UTC, BakasaRus commented on Sources/Styles/Layouts/main.css
> +    vertical-align: center;
На странице оно не работает, хоть и написано синтаксически верно

2022-10-17 11:19 UTC, BakasaRus commented on Sources/Styles/Layouts/body.css
> +    background-color: #22272e;
Посмотреть способы задания цветов

2022-10-17 11:19 UTC, BakasaRus commented on Sources/Styles/Layouts/footer.css
> +    text-indent: 5px;
Что это такое?

2022-10-25 13:56 UTC, AndrewZzz24 commented on Sources/Styles/Layouts/footer.css
> +    padding: 15px 1em 15px 1em;
em - размер шрифта. Если размер шрифта задан font-size: 10px, то 1em = 10px
Лучше всего использовать em и px.
Также существуют 
EM - не имеет расшифровки, ассоциируется всегда с размером шрифта (font-size)
PX - пиксель
PT - пункт
PC - пика
CM - сантиметр
IN - дюйм
Как использовать
![image](https://user-images.githubusercontent.com/70968410/197792737-cdbd1e9d-5d71-486d-bb66-3e2d10ea116a.png)

2022-10-25 15:17 UTC, AndrewZzz24 commented on Sources/Styles/Layouts/main.css
> +    vertical-align: center;
В данном случае vertical-align не работает, так как его использование некорректно.
Оно применяется только к строчным элементам inline или строчным блокам inline-block.
или применяется к ячейке таблицы, выравнивание влияет на содержимое ячейки, а не на неё саму.

В данном случае мы не используем display: inline-block и также не используем таблицы.

2022-10-25 15:21 UTC, AndrewZzz24 commented on Sources/Styles/Layouts/body.css
> +    background-color: #22272e;
Существует несколько способов задание цветов:
1) Задание цвета в CSS по его названию (colour: black)
2) Задание цвета в системе HEX (16я система счисления) - как в примере.
В начале указывается символ # (хэш) за которым далее следует три пары значений цвета, каждая пара представляет собой три разных цветовых канала. Первая пара для красного, вторая для зеленого и третья для синего канала соответственно 
3) Задание цвета с помощью RGB (color: rgb(255,255,255))
4) Задание цвета в CSS3 в системе HSL (color: hsl(0,0%,0%) )
HSL - (Hue Saturation Lightness) - в этой системе, цвет задается тремя параметрами: оттенком, насыщенностью и яркостью

2022-10-25 15:22 UTC, AndrewZzz24 commented on Sources/Styles/Layouts/footer.css
> +    text-indent: 5px;
text-indent - свойство, которое задает отступ перед строкой в текстовом блоке.

2022-10-31 12:30 UTC, BakasaRus approved these changes

2022-11-01 13:16 UTC, merged